[package]
name = "dice"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22.1"
chacha20 = { git="https://github.com/nstilt1/stream-ciphers-rng", branch="production", default-features = false, features = ["rng"]}
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.72"
midly = "0.5.3"
rand = { version = "0.10", default-features = false }
rayon = "1.11.0"
serde = "1.0.215"
serde_json = "1.0.132"
serde-wasm-bindgen = "0.6"
sha2 = "0.10"
statistics = { path="../statistics" }
wasm-bindgen = { version = "0.2.108" }
wasm-bindgen-rayon = "1.3.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4', "--enable-bulk-memory", "--enable-atomics", "--enable-threads", "--enable-sign-ext", "--enable-nontrapping-float-to-int"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false               # removes debug info from the generated js glue code
demangle-name-section = false       # controls whether function names are readable in stack traces
dwarf-debug-info = false            # removes DWARF debug info
omit-default-module-path = false    # removes default module path
