/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_bruteforceresult_free: (a: number, b: number) => void;
export const __wbg_doublesimulationresult_free: (a: number, b: number) => void;
export const __wbg_roll_free: (a: number, b: number) => void;
export const __wbg_simulationresult_free: (a: number, b: number) => void;
export const __wbg_statsresult_free: (a: number, b: number) => void;
export const analyze_dice: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => number;
export const brute_force: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => number;
export const bruteforceresult_best_mean_dice_threshold: (a: number) => number;
export const bruteforceresult_best_mean_target_score: (a: number) => number;
export const bruteforceresult_best_mean_target_score_results: (a: number) => number;
export const bruteforceresult_best_median_dice_threshold: (a: number) => number;
export const bruteforceresult_best_median_target_score: (a: number) => number;
export const bruteforceresult_best_median_target_score_results: (a: number) => number;
export const dice_stats: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const doublesimulationresult_max_possible_scores: (a: number) => number;
export const doublesimulationresult_max_scores_with_conditional_pass: (a: number) => number;
export const roll_num_dice: (a: number) => number;
export const roll_p_bust: (a: number) => number;
export const roll_p_score: (a: number) => number;
export const simulationresult_maximum: (a: number) => number;
export const simulationresult_results: (a: number) => [number, number];
export const statsresult_roll_probabilities: (a: number) => [number, number];
export const simulationresult_mean: (a: number) => number;
export const simulationresult_median: (a: number) => number;
export const simulationresult_minimum: (a: number) => number;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
